version: '3'
services:
    nginx:
        container_name: nginx_container
        image: nginx:alpine
        volumes:
            - "./server/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./server/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./server/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - ${NGINX_PORT}:80
            - ${NGINX_SECURE_PORT}:443
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysql
    php:
        container_name: php_container
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        volumes:
            - "./server/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
    phpmyadmin:
        container_name: phpmyadmin_container
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysql
    mysql:
        container_name: mysql_container
        image: mysql:${MYSQL_VERSION}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
